[package]
name = "mssql-db-connect"
version = "0.1.0"
authors = ["tims <tsteeman@jibes.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odbc = "0.17"
log = "0.4.0"
env_logger = "0.7.1"
dotenv = "0.15.0"